### ISSUE TITLE
Error in preprocess variants, apparently related to POS

### ISSUE THREAD

**Issue by daler** [varlociraptor/varlociraptor#225] opened 2021-10-13 21:15 UTC
I'm getting an error that, best I can tell, is related to particular yet apparently arbitrary POS coordinates. Please see below for example inputs to reproduce this behavior.

(This using v4.5.0).

I found that the following command:

```bash
RUST_BACKTRACE=1 varlociraptor preprocess variants \
  GRCm38.fa.gz \
  --log-mode each-record  \
  --bam a.bam  \
  --candidates last_line_fails.vcf \
  > sample.obs.bcf
```

Results in the following error:

```
No deletion CIGAR operations found in first 10000 alignments. Varlociraptor will be unable to estimate the sampling bias for deletions.
No deletion CIGAR operations found in first 10000 alignments. Varlociraptor will be unable to estimate the sampling bias for insertions.
Processing record at 1:7780413
Processing record at 1:7780414
Processing record at 1:7780415
Processing record at 1:7780418
Processing record at 1:7780419
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])', /opt/conda/conda-bld/varlociraptor_1633603011719/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.38.2/src/bcf/record.rs:581:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: rust_htslib::bcf::record::Record::set_alleles
   4: varlociraptor::calling::variants::Call::write_preprocessed_record
   5: varlociraptor::calling::variants::preprocessing::ObservationProcessor<R>::process
   6: varlociraptor::cli::run
   7: varlociraptor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If I change the last line of that failing VCF from

```
1       7780419 .       T       G       49.38
```

to

```
1       7780420 .       T       G       49.38
```

that is, simply increment POS by one, then there is no error. I cannot explain it but it's the only way I found to avoid the error! Of course, a full GATK-called VCF has many such problematic lines.

Example input files are below.

<details>
<summary>

`samtools view -h a.bam`

</summary>

```
@HD     VN:1.6  SO:coordinate
@SQ     SN:1    LN:195471971
@PG     ID:samtools     PN:samtools     VN:1.11 CL:samtools view -h a.sam
A00428:242:HHTJJDSXY:2:1166:9435:10066  83      1       7780166 60      151M    =       7779972 -345    ATGTAGAAATGCCTGGTAAGTAGGGACTATTAATAATGTTCATACCAGCATCCTGAGAACAAGATTCAGTAACTAATAAACAAAAACAAACACACCAGCCAGGTCTAGATGCACTGGATCATCACACAGATGCTAATGGATGAGTGTGAGT BECCGEEEDEFFFEECCEGCCGEEEEFCDDCEDCEDECDEFDCEFFGFFDEFFEEGEEEFEGEDDEFGCCEEFCEDCEEEFEEEEDEDEEEDEDEEFEEEFDBDEBFDCDEEDEDDDCDEC+EDEDEFDCDEEBDCDDDBCDFBDAEDGCB MC:Z:151M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:58
A00428:242:HHTJJDSXY:2:2456:12500:23735 83      1       7780201 60      151M    =       7779971 -381    ATGTTCATACCAGCATCCTGAGAACAAGATTCAGTAACTAATAAACAAAAACAAACACACCAGCCAGGTCTAGATGCACTGGATCATCACACAGATGCTAATGGATGAGTGTGAGTTTCTGACTCATGTGAGAAAGCGGTCTGCCTAATCT BE5DEFDCE+FGFFDEFFEEGEEEFEGED*EFGCCEEFCEDCEEEFEEEEEFEE;FEFEFFGFFFGECEFCGEDEF;E<EEEDEFCDEEFDEFDCDEEBDCDDDCDDFBDBDDFBCCDEDDDEDECDBDDFDDDFE<DBCDDEEEAECEFB MC:Z:150M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:43
A00428:242:HHTJJDSXY:2:1335:25590:17127 147     1       7780206 60      151M    =       7780075 -282    CATACCAGCATCCTGAGAACAAGATTCAGTAACTAATAAACAAAAACAAACACACCAGCCAGGTCTAGATGCACTGGATCATCACACAGATGCTAATGGATGAGTGTGAGTTTCTGACTCATGTGAGAAAGCGGTCTGCCTAATCTTAGGT AA@B7BCBCAACCBBCABBCBD4A@BCD@@BBC@BA@BBBCBBCCCCBBBCBC7DDE876E5AC7A;CBC,DCDCCCBCDBCDCDC7E6BCDDACBCCCBCCEACACCEABBCDCCCDCD8CACCECCCED;CAC:CDDDACCCDBDG<BB MC:Z:150M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:22
A00428:242:HHTJJDSXY:2:2178:28646:25927 99      1       7780241 60      151M    =       7780634 544     ATAAACAAAAACAAACACACCAGCCAGGTCTAGATGCACTGGATCATCACACAGATGCTAATGGATGAGTGTGAGTTTCTGACTCATGTGAGAAAGCGGTCTGCCTAATCTTAGGTATTTTCTATGGCAGCAAGAGAAAAATCACTTGGCG BDCCDADCCC=ADCCBDBDBDDEEDDEEDDF:E+CEE:BFEEDCDDCDDBDBDEDCE>F9CDFEDCFEFEFEFEFEEEEGFECGEEDFEFEFEDDFF=FEEGFFEGC9DEGECFFECDEEEEGCDFFFEFFEDFEFEDDDDDEECGEFFF; MC:Z:151M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:20
A00428:242:HHTJJDSXY:2:1510:3866:31548  83      1       7780245 60      151M    =       7780071 -325    ACAAAAACAAACACACCAGCCAGGTCTAGATGCACTGGATCATCACACAGATGCTAATGGATGAGTGTGAGTTTCTGACTCATGTGAGAAAGCGGTCTGCCTAATCTTAGGTATTTTCTATGGCAGCAAGAGAAAAATCACTTGGCGGGGG CFEEEEEFEEEFEFEFFGFFFGECEFCGEDEFFEFEEEDEFDEFEFEFGEDEFFCEDEEEDEEGCECEEGCDDEFEEEFEFDECEDFDEEFE<DBDEDEEEBDCDECBFDBBCCCCDEBCDDEEFEEDFDFDDDDDCDECDCDDE;EDEEB MC:Z:151M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:20
A00428:242:HHTJJDSXY:2:1129:11125:13401 99      1       7780318 60      97M51S  =       7780564 397     TCTGACTCATGTGAGAAAGCGGTCTGCCTAATCTTAGGTATTTTCTATGGCAGCAAGAGAAAAATCACTTGGCGGGGGGGGGGGGGGGGGGGGGGGACAGGGGGGGGGGGGGGGTGGGTTTGGTGGGGGGGGGTTAACAATATTTTTT    BEGEEAFDDCDC>DEDCCEE<EDDFEEDFB=CDFDBEEDBC.DD,FBCEEEDEEDCEDEDCDDCCDEC@EFFF4FFFFFFFFFFFFFFFFFFFFFF)));F::F:,,,,,FF:,+9:F+--,F9FFF,++FF9*,')5(*+5*,E;;E    MC:Z:151M       MD:Z:97   PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:97 XS:i:32
A00428:242:HHTJJDSXY:2:1445:23005:3599  163     1       7780384 6       30S25M39S       =       7780652 419     GGGGTGGGGGGGGGGAGCATGAGACAATGGACTTGGCGGGGGGGGGGGGGGGGGGTGGGGGGGGGGGTGGGGGGGGGGGGTGGGGGGGGGGGGG  :.>.---;--,D::,)D-)+D)-7))*+,,))0-DD,;9DDDDD+DDDD8DD88+*+8D++D++D8D*DD+8D++DD7+D*67+DDDD7DD7+D  MC:Z:151M       MD:Z:25 PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:25 XS:i:41
A00428:242:HHTJJDSXY:2:2564:25337:11616 147     1       7780424 60      85S66M  =       7780025 -465    CCCCCCCCCCCCCGCCCCCCCCCCGCCCCCCCCCCCCCCCCGCCCCCCCCCCCCCCGCCCCCCCCCCCCCCCCCAACGGCGGGGTGTTGGGGTAGGGTTGTGGTGGTCGTGGTATCACTTAAGTGTTAGAGGTCCTAGAACAAGGGTTAAT 6+C+C6++++B6.,C+6+6+6+C$,C+6C777C++C+C+7$,+77D7+C+++++7$,77+7+777D++777+8+,8$+,$+CCA(4)(CCCA'ECCABCAC6A5CAC1ACC5ABCDCDBAC=ACABAECECAC:DA>8<CDC?99AECECB SA:Z:14,63050337,+,105S37M9S,19,0;4,108679154,-,30S33M88S,4,0;    MC:Z:151M       MD:Z:66 PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:66 XS:i:0
A00428:242:HHTJJDSXY:2:1138:2772:31532  163     1       7780427 60      151M    =       7780666 390     GGGGTAGGGTTGTGGTGGTCGTGGTATCACTTAAGTGTTAGAGGTCCTAGAACAAGGGTTAATGAAAAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACACAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGC :EFF>ADD;;CDCDDCDD:C%C8DCABCCAECABD*DCCA9CDD9CCEADC7ACBDDDCCABBDCBBBBBB4CDCCC6ABBDCA/CCBD+DDC7DCAC7CBC7C7DECBBAA@(@BACBAAC7BBB:4D5+BA@4AACC+6B*B6A9@@:7 MC:Z:151M       MD:Z:113T37       PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:1  AS:i:146        XS:i:20
A00428:242:HHTJJDSXY:2:1223:29785:16219 2193    1       7780427 0       108H39M =       7780029 -437    GGGGTAGGGTTGTGGTGGTCGTGGTATCACTTAAGTGTT +CC5(=CC5*)A6CACCAC;ACCAABCDCDCACEDECCB SA:Z:7,90441976,-,31S45M71S,0,0;7,90441975,-,46M101S,0,1;       MC:Z:150M       MD:Z:39 PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:39 XS:i:20
A00428:242:HHTJJDSXY:2:1235:30526:7357  147     1       7780427 60      68S82M  =       7780094 -415    CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAGCCGGGGCCTGGGGGTAGGGTTGTGGTGGTCGTGGTATCACTTAAGTGTTAGAGGTCCTAGAACAAGGGTTAATGAAAAAAACAGTCATAAAG  C7C7B+++C++CC+B6C6CC66+BCC6C7CCCCCCC677C+C+DD++C7CCC+7+,/,+;+++,+,(+55CAA<66A)5A5CACCAC;A5CAABCDCDBACEACABAE7ECACDDAECCCDCEC7ABACBCCCCCCCCCDEBCDBDEEFB  SA:Z:7,90441976,-,10S45M95S,0,0;  MC:Z:151M       MD:Z:82 PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:82 XS:i:20
A00428:242:HHTJJDSXY:2:2445:13196:11412 99      1       7780460 60      151M    =       7780720 410     AGTGTTAGAGGTCCTAGAACAAGGGTTAATGAAAAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTC BFEEEC9EDEDCDDFBEDCBDCEEEDDBCCEDCCCCCCBDEDDDCBCCEDBFDDCEEEEDEFEBDEFEFEFFFGEEEDDCGEEDFEDDFEEEEGEGFFE:CEEDFFFFEDFEEECC=FGFEDE=FEFEEFFFEFFFEFFGECCEEFFGEGC MC:Z:150M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:0
A00428:242:HHTJJDSXY:2:1338:4652:31000  163     1       7780464 60      151M    =       7780640 327     TTAGAGGTCCTAGAACAAGGGTTAATGAAAAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTCTGAA BDCFFDDCDCEADCBA7BDDDCCABBDCBBBBBBACDCCCBABBDCAECCBDDDDCDDCA5DD6DCDDDECCCBBAECCBDCBBDCCCCECEDDCBACBACCCCBBDCBB3@:CDCBAB:C7CBBCBCBC[W::sam_parse1] unrecognized mate reference name "7"; treated as unmapped
CCBCBCB@@BACCCACBDCB?   MC:Z:151M       MD:Z:151        PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:0
A00428:242:HHTJJDSXY:2:2652:18566:16548 147     1       7780466 60      151M    =       7780081 -536    AGAGGTCCTAGAACAATGTTTTTTGAAAAAAACAGTCATCAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTGACCAGCTCTCTGAAGT B5DB(A6B2:4BB5B*A(AA)))BABB8,9B*CD(B65B+,DBCDCCBD5B8CEDD*DECCEACCDDCDDC:*7CD,E*CC<ABCD,CDC6CC8DD:<CC6C75A7BA*;DD(CBC;C5CAB6C,C0,CCEDDC+CDDEDDCECD8-EGBB MC:Z:151M       MD:Z:16G1G2A0A16A94T16    PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:6  AS:i:121        XS:i:20
A00428:242:HHTJJDSXY:2:1307:16315:2065  97      1       7780474 60      151M    *       90441976        0       TAGAACAAGGGTTAATGAAAAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTCTGAAGTTTGGGTTA BCFDDADCEEDCDBCCEDCCCCCCBDEDDDCBCCEDBFDDCEEEEDEEDBDEEDEDEEEFDE9CCBGEEDFEDDFEEEEGEGFFEDCEEDFFFFEDFEEECC=FGF8DE=FEFEEFFFEFFFEFFGECCEEFFGEGEGFEDFEEEFFFEEA MC:Z:25S45M81S    MD:Z:151        PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:19
A00428:242:HHTJJDSXY:2:1569:3586:22420  121     1       7780481 60      151M    =       7780481 0       AGGGTTAATGAAAAAAACAGTCAGAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTCTGAAGTTTGGGTTATGAAGGT EEE58CEDEEEEEEEEEFGCEFG+<-GEE:EF->EEFFG;FE,GEEGCEEFFEFFEEEFE:=GEE=GC*9FF:FEEE-EF;EGEEDDCE*CC9D<E<DDCD<D9DBCDDDDFDDDFEE=B>>EFEEDEDEDD2FBCCDDCACBCDCEAECB MD:Z:23T127     PG:Z:MarkDuplicates       RG:Z:sample1    NM:i:1  AS:i:146        XS:i:24
A00428:242:HHTJJDSXY:2:1569:3586:22420  181     1       7780481 0       *       =       7780481 0       CACCACACCCTCCAGCCCCCCCCCGCCACCCTCAGAGCGACACTAACACCCACCCGCCCGCCCACCCGCCGCACGCCTGCCCCCAACCTCGACCCCCCACCCCCCCCCCACTACTCCCCCTACTTCCCAGTCCACCGCACCCCAGCACTCT A*CC*+*B6,(C5/,6B66++CC$,++*7+,(+/*;,$**+*7',*+*++C*CD;,D+$,++D77+;8+$,D*/,+8(,8DD++,*+,(0**D+D8D+*D++++++9+D*,'*D(+D,,9(+-*)D,,0)),D+D%-,+,,--1.:-F+E+ MC:Z:151M       PG:Z:MarkDuplicates       RG:Z:sample1    AS:i:0  XS:i:0
A00428:242:HHTJJDSXY:2:1559:31485:15499 163     1       7780491 60      151M    =       7780778 438     AAAAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTCTGAAGTTTGGGTTATGAAGGTATGACTCTCC BCDDEBBADDCCCBABBDCAECCBDDDDCDDCACDDCDCDDDECCCBBAECCBDCBBDCCCCECEDD6BACCBDDDDCBDCCCAA;DEDCBC;DCDCCCCCBCCCCDDDB@@BBCCDBDBDCBACBABCCCBB@@BBACCA@ABA?DBDB@ MC:Z:151M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:21
A00428:242:HHTJJDSXY:2:1276:22896:12179 163     1       7780493 60      151M    =       7780747 405     AAAAACAGTCATAAAGACTCAAGGGCAGCACAGGAGTGGCTCCAAACTCAAGAAAGTTCCTCTGGAACCAAGGGGATGTTTACGCTGATCGGTGTTGGGAGGGAGCTTACCAGCTCTCTGAAGTTTGGGTTATGAAGGTATGACTCTCCAT BCDDEACD,CCBABBDCAECCBDDDDCDDCACDDCDCDDDECCCBBAECCBDCBBDCCCCECEDDCBACCBDDDDCBDCCCAA;DEDCBC;DCDCCDDCBCCCBCDEC@@BBCCDBDBDCBACBBBBCCBB@ACA@CCB@@CB?CADBBB? MC:Z:151M       MD:Z:151  PG:Z:MarkDuplicates     RG:Z:sample1    NM:i:0  AS:i:151        XS:i:0
```
</details>

<details>
<summary>

`last_line_fails.vcf`
</summary>

```
##fileformat=VCFv4.2
##contig=<ID=1,length=195471971,assembly=GRCm38.fa.gz>
#CHROM  POS     ID      REF     ALT     QUAL
1       7780413 .       GAA     G       44.96
1       7780414 .       A       G,*     37.02
1       7780415 .       A       G,*     37.02
1       7780418 .       C       G,*     35.95
1       7780419 .       T       G       49.38
```
</details>

<details>
<summary>

`last_line_works.vcf`
</summary>

```
##fileformat=VCFv4.2
##contig=<ID=1,length=195471971,assembly=GRCm38.fa.gz>
#CHROM  POS     ID      REF     ALT     QUAL
1       7780413 .       GAA     G       44.96
1       7780414 .       A       G,*     37.02
1       7780415 .       A       G,*     37.02
1       7780418 .       C       G,*     35.95
1       7780420 .       T       G       49.38
```
</details>

**Comment by johanneskoester** [comment] 2021-11-17 07:59
Thanks a lot for reporting, and sorry for the delay. I'll have a look into this as soon as possible.

**Comment by johanneskoester** [comment] 2021-11-23 15:15
Hi @daler I just tried to reproduce this with the latest version (4.7) and there was no issue. I think this was a temporary bug in rust-htslib, which has been fixed in the meantime and therefore does not occur anymore because we have updated to a newer version of rust-htslib here. Please reopen if the issue persists for you.

**Comment by johanneskoester** [comment] 2021-11-23 15:16
And btw. I am excited to see that you are considering Varlociraptor! Any feedback is very welcome!

**Closed by johanneskoester** 2021-11-23 15:15 UTC
